# fly.toml app configuration file generated for netflix-sample on 2024-03-11T14:25:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "netflix-sample"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "512mb"
