/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const UseQueryLazyImport = createFileRoute('/useQuery')()
const EmbeddingLazyImport = createFileRoute('/embedding')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UseQueryLazyRoute = UseQueryLazyImport.update({
  path: '/useQuery',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/useQuery.lazy').then((d) => d.Route))

const EmbeddingLazyRoute = EmbeddingLazyImport.update({
  path: '/embedding',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/embedding.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/embedding': {
      preLoaderRoute: typeof EmbeddingLazyImport
      parentRoute: typeof rootRoute
    }
    '/useQuery': {
      preLoaderRoute: typeof UseQueryLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  EmbeddingLazyRoute,
  UseQueryLazyRoute,
])

/* prettier-ignore-end */
