/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LatitudeEmbed {
        "first": string;
        "last": string;
        "middle": string;
    }
}
declare global {
    interface HTMLLatitudeEmbedElement extends Components.LatitudeEmbed, HTMLStencilElement {
    }
    var HTMLLatitudeEmbedElement: {
        prototype: HTMLLatitudeEmbedElement;
        new (): HTMLLatitudeEmbedElement;
    };
    interface HTMLElementTagNameMap {
        "latitude-embed": HTMLLatitudeEmbedElement;
    }
}
declare namespace LocalJSX {
    interface LatitudeEmbed {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface IntrinsicElements {
        "latitude-embed": LatitudeEmbed;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "latitude-embed": LocalJSX.LatitudeEmbed & JSXBase.HTMLAttributes<HTMLLatitudeEmbedElement>;
        }
    }
}
