name: Pre-Release

on:
  push:
    branches:
      - canary

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  pre_release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: true

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          CLI_SENTRY_DSN: ${{ secrets.CLI_SENTRY_DSN }}
          CLI_SENTRY_ENABLED: 'true'
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          LATITUDE_SERVER_HOST: ${{ secrets.LATITUDE_SERVER_HOST }}
          LATITUDE_SERVER_PORT: ${{ secrets.LATITUDE_SERVER_PORT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TELEMETRY_CLIENT_KEY: ${{ secrets.TELEMETRY_CLIENT_KEY }}
          TELEMETRY_URL: ${{ secrets.TELEMETRY_URL }}
