name: Tests suite

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Specify node versions you want to test against

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Checkout HEAD^

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: |
          pnpm install

          # tells Turbo to only run the script (build or test in this case) for the packages
      - name: Use Turbo to build affected packages
        run: pnpm turbo run build --cache-dir=.turbo --filter=@latitude-data/*{./packages/*}[HEAD^1] --filter=@latitude-data/*{./apps/*}[HEAD^1]

      - name: Run tests
        run: pnpm turbo run test --filter=@latitude-data/*{./packages/*}[HEAD^1] --filter=@latitude-data/*{./apps/*}[HEAD^1]
